project 'Tutorial.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'Yams'

  # Pods for Tutorial
  target 'TutorialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TutorialUITests' do
    # Pods for testing
  end
end
